const shoppingItemsArr = [
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-1.png',
    product: 'Acer 7 Ryzen 17QW',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 499,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-1.png',
    product: 'Modem Netgear 765ppq',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 129,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-1.png',
    product: 'Tipkovnica Logitech PAQ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 14,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-1.png',
    product: 'DELL OptiFLEX 256ssd',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 799,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-1.png',
    product: 'Monitor 27" S56Z 4ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 1199,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-1.png',
    product: 'Adobe Reader licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 511,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-2.png',
    product: 'ACER office 1tb 5500u',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 449,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-2.png',
    product: 'Network Office XII 2022i',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 139,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-2.png',
    product: 'Mouse Razer 993UZH',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 15,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-2.png',
    product: 'Gaming HybridFast 1tb Ryzen 9',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 699,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-2.png',
    product: 'Monitor 20" g56Z 4ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 277,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-2.png',
    product: 'Adobe After Effects licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 560,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-3.png',
    product: 'Lenovo V15 G2 Ryzen',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 279,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-3.png',
    product: 'Modem Samsung 99ghz',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 149,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-3.png',
    product: 'Keyboard Colorful Gaming',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 18,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-3.png',
    product: 'Gigabyte GeForce 3060X GAMe',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 249,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-3.png',
    product: 'Monitor 27" S5OP IPS',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 929,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-3.png',
    product: 'Adobe Illustrator licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 522,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-4.png',
    product: 'HP Professional 1tb IIT',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 499,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-4.png',
    product: 'Network Ethernet UltraZ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 118,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-4.png',
    product: 'Keyboard Gaming Analogue 8z',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 17,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-4.png',
    product: 'Monitor 23.8" Sth6Z 8ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 629,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-4.png',
    product: 'Gaming UltraFast GeForce 2040ti',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 559,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-4.png',
    product: 'Adobe Photoshop licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 519,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-5.png',
    product: 'Laptop GIGABYTE 512ssd',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 599,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-5.png',
    product: 'Home Network 6x',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 119,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-5.png',
    product: 'Joystick Gaming Hybrid 221',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 24,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-5.png',
    product: 'IBM business Office 4zz',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 719,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-5.png',
    product: 'Monitor 25" W233U TN 4ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 289,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-5.png',
    product: 'Adobe Xd licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 567,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-6.png',
    product: 'HP laptop Professional',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 399,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-6.png',
    product: 'MULTI network',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 169,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-6.png',
    product: 'Slušalice 99db ULTRA',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 29,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-6.png',
    product: 'VICTUS GamingUltra',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 549,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-6.png',
    product: 'Monitor 23" QHD 144hz',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 533,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-6.png',
    product: 'Microsoft Windows 10 licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 999,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-7.png',
    product: 'ASUS Chromebook 315x',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 889,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-7.png',
    product: 'Ethernet ZZp223',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 117,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-7.png',
    product: 'Smart cable AAIX',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 19,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-7.png',
    product: 'ACER Nitro 445z',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 759,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-7.png',
    product: 'Monitor 28" 75hz 4ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 559,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-7.png',
    product: 'Autodesk Maya licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 577,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-8.png',
    product: 'ASUS TUF F15 Gaming',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 299,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-8.png',
    product: 'Netgear cable 554H',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 156,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-8.png',
    product: 'USB Sony 500gb',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 144,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-8.png',
    product: 'Gaming Iron 2022',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 179,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-8.png',
    product: 'Monitor 27" Samsung 144hz',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 399,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-8.png',
    product: 'Cinema 4D licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 739,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-9.png',
    product: 'Apple Air 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 859,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-9.png',
    product: 'Netgear 2 2019air',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 123,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-9.png',
    product: 'Joystick SONY CPU',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 49,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-9.png',
    product: 'IBM newMedia 44T',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 669,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-9.png',
    product: 'Monitor 32" S998 IPS',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 659,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-9.png',
    product: 'Autoesk Autocad licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 698,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-10.png',
    product: 'Laptop Philips max2022',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 999,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-10.png',
    product: 'Netgear AJN 992',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 109,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-10.png',
    product: 'Podloga Razer UI',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 27,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-10.png',
    product: 'SONY lastCPU',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 1249,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-10.png',
    product: 'Monitor 22.8" 75hz 4ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 633,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-10.png',
    product: 'Office 365 licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 1033,
  },
  {
    category: 'laptop',
    img: '/src/styles/img/laptop/laptop-11.png',
    product: 'Acer 6',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 199,
  },
  {
    category: 'network',
    img: '/src/styles/img/network/network-11.png',
    product: 'Netgear Multitap iCC',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 189,
  },
  {
    category: 'accessories',
    img: '/src/styles/img/accessories/periferija-11.png',
    product: 'Mouse Logitech ARPII',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 59,
  },
  {
    category: 'desktop',
    img: '/src/styles/img/desktop/desktop-11.png',
    product: 'ASUS PCR08',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 1199,
  },
  {
    category: 'monitori',
    img: '/src/styles/img/monitori/monitor-11.png',
    product: 'Monitor 25" 33i 5ms',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 688,
  },
  {
    category: 'software',
    img: '/src/styles/img/software/software-11.png',
    product: 'SkectUp licence',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 1088,
  },
];
